-- Seed data for Aqua-AI database
-- Sample locations and initial data

-- Insert sample locations
INSERT INTO locations (name, state, district, latitude, longitude, water_body_type, water_body_name, population_affected) VALUES
('Ganga at Varanasi', 'Uttar Pradesh', 'Varanasi', 25.3176, 82.9739, 'river', 'Ganga', 1500000),
('Yamuna at Delhi', 'Delhi', 'Central Delhi', 28.6139, 77.2090, 'river', 'Yamuna', 2000000),
('Godavari at Nashik', 'Maharashtra', 'Nashik', 19.9975, 73.7898, 'river', 'Godavari', 800000),
('Krishna at Vijayawada', 'Andhra Pradesh', 'Krishna', 16.5062, 80.6480, 'river', 'Krishna', 1200000),
('Narmada at Jabalpur', 'Madhya Pradesh', 'Jabalpur', 23.1815, 79.9864, 'river', 'Narmada', 600000),
('Brahmaputra at Guwahati', 'Assam', 'Kamrup', 26.1445, 91.7362, 'river', 'Brahmaputra', 900000),
('Cauvery at Mysore', 'Karnataka', 'Mysore', 12.2958, 76.6394, 'river', 'Cauvery', 700000),
('Sabarmati at Ahmedabad', 'Gujarat', 'Ahmedabad', 23.0225, 72.5714, 'river', 'Sabarmati', 1100000),
('Hooghly at Kolkata', 'West Bengal', 'Kolkata', 22.5726, 88.3639, 'river', 'Hooghly', 1800000),
('Tapi at Surat', 'Gujarat', 'Surat', 21.1702, 72.8311, 'river', 'Tapi', 500000);

-- Insert sample water quality readings (last 30 days)
-- This would typically be generated by the data pipeline
-- For demo purposes, we'll insert some sample data

-- Sample readings for Ganga at Varanasi
INSERT INTO water_quality_readings (location_id, parameter_id, value, measurement_date, source, quality_score) VALUES
(1, 1, 8.5, CURRENT_DATE - INTERVAL '1 day', 'government', 45), -- BOD
(1, 2, 650, CURRENT_DATE - INTERVAL '1 day', 'government', 55), -- TDS
(1, 3, 7.8, CURRENT_DATE - INTERVAL '1 day', 'government', 75), -- pH
(1, 4, 4.2, CURRENT_DATE - INTERVAL '1 day', 'government', 40), -- DO
(1, 5, 0.15, CURRENT_DATE - INTERVAL '1 day', 'government', 25), -- Lead
(1, 6, 0.008, CURRENT_DATE - INTERVAL '1 day', 'government', 30), -- Mercury
(1, 7, 45.3, CURRENT_DATE - INTERVAL '1 day', 'government', 20), -- Coliform
(1, 8, 85, CURRENT_DATE - INTERVAL '1 day', 'government', 35); -- Nitrates

-- Sample readings for Yamuna at Delhi
INSERT INTO water_quality_readings (location_id, parameter_id, value, measurement_date, source, quality_score) VALUES
(2, 1, 15.2, CURRENT_DATE - INTERVAL '2 hours', 'government', 15), -- BOD
(2, 2, 850, CURRENT_DATE - INTERVAL '2 hours', 'government', 40), -- TDS
(2, 3, 8.1, CURRENT_DATE - INTERVAL '2 hours', 'government', 60), -- pH
(2, 4, 2.8, CURRENT_DATE - INTERVAL '2 hours', 'government', 25), -- DO
(2, 5, 0.25, CURRENT_DATE - INTERVAL '2 hours', 'government', 10), -- Lead
(2, 6, 0.015, CURRENT_DATE - INTERVAL '2 hours', 'government', 15), -- Mercury
(2, 7, 120.5, CURRENT_DATE - INTERVAL '2 hours', 'government', 5), -- Coliform
(2, 8, 150, CURRENT_DATE - INTERVAL '2 hours', 'government', 20); -- Nitrates

-- Sample readings for Godavari at Nashik
INSERT INTO water_quality_readings (location_id, parameter_id, value, measurement_date, source, quality_score) VALUES
(3, 1, 4.8, CURRENT_DATE - INTERVAL '6 hours', 'government', 65), -- BOD
(3, 2, 420, CURRENT_DATE - INTERVAL '6 hours', 'government', 80), -- TDS
(3, 3, 7.2, CURRENT_DATE - INTERVAL '6 hours', 'government', 85), -- pH
(3, 4, 5.8, CURRENT_DATE - INTERVAL '6 hours', 'government', 70), -- DO
(3, 5, 0.08, CURRENT_DATE - INTERVAL '6 hours', 'government', 60), -- Lead
(3, 6, 0.003, CURRENT_DATE - INTERVAL '6 hours', 'government', 75), -- Mercury
(3, 7, 8.2, CURRENT_DATE - INTERVAL '6 hours', 'government', 80), -- Coliform
(3, 8, 35, CURRENT_DATE - INTERVAL '6 hours', 'government', 85); -- Nitrates

-- Sample readings for Krishna at Vijayawada
INSERT INTO water_quality_readings (location_id, parameter_id, value, measurement_date, source, quality_score) VALUES
(4, 1, 2.1, CURRENT_DATE - INTERVAL '12 hours', 'government', 90), -- BOD
(4, 2, 380, CURRENT_DATE - INTERVAL '12 hours', 'government', 95), -- TDS
(4, 3, 7.4, CURRENT_DATE - INTERVAL '12 hours', 'government', 90), -- pH
(4, 4, 6.8, CURRENT_DATE - INTERVAL '12 hours', 'government', 85), -- DO
(4, 5, 0.02, CURRENT_DATE - INTERVAL '12 hours', 'government', 90), -- Lead
(4, 6, 0.001, CURRENT_DATE - INTERVAL '12 hours', 'government', 95), -- Mercury
(4, 7, 3.5, CURRENT_DATE - INTERVAL '12 hours', 'government', 95), -- Coliform
(4, 8, 25, CURRENT_DATE - INTERVAL '12 hours', 'government', 90); -- Nitrates

-- Insert sample AI predictions
INSERT INTO ai_predictions (location_id, parameter_id, predicted_value, confidence_score, prediction_date, forecast_hours, model_version, risk_level) VALUES
(1, 1, 9.2, 78.5, CURRENT_DATE + INTERVAL '24 hours', 24, 'v1.2', 'high'),
(1, 2, 680, 82.3, CURRENT_DATE + INTERVAL '24 hours', 24, 'v1.2', 'medium'),
(2, 1, 16.8, 85.2, CURRENT_DATE + INTERVAL '48 hours', 48, 'v1.2', 'critical'),
(2, 4, 2.1, 79.8, CURRENT_DATE + INTERVAL '48 hours', 48, 'v1.2', 'critical'),
(3, 1, 5.1, 72.4, CURRENT_DATE + INTERVAL '24 hours', 24, 'v1.2', 'medium'),
(4, 1, 2.3, 88.7, CURRENT_DATE + INTERVAL '24 hours', 24, 'v1.2', 'low');

-- Insert sample alerts
INSERT INTO alerts (location_id, parameter_id, alert_type, severity, message, threshold_value, actual_value, triggered_at) VALUES
(1, 1, 'threshold_exceeded', 'high', 'BOD levels exceed safe limits', 6.0, 8.5, CURRENT_TIMESTAMP - INTERVAL '2 hours'),
(1, 5, 'threshold_exceeded', 'critical', 'Lead contamination critical', 0.1, 0.15, CURRENT_TIMESTAMP - INTERVAL '4 hours'),
(2, 1, 'threshold_exceeded', 'critical', 'BOD levels critically high', 10.0, 15.2, CURRENT_TIMESTAMP - INTERVAL '1 hour'),
(2, 7, 'threshold_exceeded', 'critical', 'Bacterial contamination critical', 50.0, 120.5, CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
(3, 1, 'threshold_exceeded', 'medium', 'BOD levels moderately high', 6.0, 4.8, CURRENT_TIMESTAMP - INTERVAL '6 hours');

-- Insert sample weather data
INSERT INTO weather_data (location_id, temperature, humidity, pressure, wind_speed, wind_direction, precipitation, weather_condition, measurement_date) VALUES
(1, 28.5, 65, 1013.2, 12.3, 180, 0.0, 'Clear', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
(2, 32.1, 58, 1008.7, 8.9, 225, 0.0, 'Hazy', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
(3, 26.8, 72, 1015.4, 15.2, 90, 2.5, 'Light Rain', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
(4, 29.3, 68, 1012.1, 10.7, 135, 0.0, 'Partly Cloudy', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
(5, 27.9, 70, 1014.8, 11.4, 270, 0.0, 'Clear', CURRENT_TIMESTAMP - INTERVAL '1 hour');

-- Insert sample water quality index calculations
INSERT INTO water_quality_index (location_id, wqi_score, wqi_category, calculation_date, parameters_used, calculation_method) VALUES
(1, 45.2, 'Poor', CURRENT_DATE - INTERVAL '1 day', '["BOD", "TDS", "pH", "DO", "Lead", "Mercury", "Coliform", "Nitrates"]', 'weighted_average'),
(2, 28.7, 'Very Poor', CURRENT_DATE - INTERVAL '2 hours', '["BOD", "TDS", "pH", "DO", "Lead", "Mercury", "Coliform", "Nitrates"]', 'weighted_average'),
(3, 72.8, 'Good', CURRENT_DATE - INTERVAL '6 hours', '["BOD", "TDS", "pH", "DO", "Lead", "Mercury", "Coliform", "Nitrates"]', 'weighted_average'),
(4, 89.3, 'Excellent', CURRENT_DATE - INTERVAL '12 hours', '["BOD", "TDS", "pH", "DO", "Lead", "Mercury", "Coliform", "Nitrates"]', 'weighted_average'),
(5, 65.4, 'Fair', CURRENT_DATE - INTERVAL '1 day', '["BOD", "TDS", "pH", "DO", "Lead", "Mercury", "Coliform", "Nitrates"]', 'weighted_average');

-- Insert sample community reports
INSERT INTO community_reports (location_id, user_id, report_type, description, latitude, longitude, status, verified) VALUES
(1, 'user_001', 'pollution_incident', 'Saw industrial waste being dumped into the river near the ghat', 25.3200, 82.9750, 'pending', false),
(2, 'user_002', 'water_quality', 'Water appears discolored and has foul smell', 28.6150, 77.2100, 'verified', true),
(3, 'user_003', 'positive_change', 'Water quality seems to have improved after recent cleanup', 19.9980, 73.7900, 'verified', true),
(4, 'user_004', 'pollution_incident', 'Dead fish found floating in the river', 16.5070, 80.6490, 'pending', false);

-- Insert data sources
INSERT INTO data_sources (name, source_type, api_url, last_fetch, fetch_frequency, status) VALUES
('Data.gov.in Water Quality', 'government', 'https://api.data.gov.in/rest/water-quality', CURRENT_TIMESTAMP - INTERVAL '1 hour', '1 hour', 'active'),
('CPCB Monitoring Network', 'government', 'https://cpcb.nic.in/api/water-quality', CURRENT_TIMESTAMP - INTERVAL '2 hours', '2 hours', 'active'),
('Ministry of Jal Shakti', 'government', 'https://jal.gov.in/api/water-data', CURRENT_TIMESTAMP - INTERVAL '3 hours', '3 hours', 'active'),
('OpenWeatherMap', 'sensor', 'https://api.openweathermap.org/data/2.5/weather', CURRENT_TIMESTAMP - INTERVAL '30 minutes', '30 minutes', 'active'),
('Community Reports', 'community', NULL, CURRENT_TIMESTAMP - INTERVAL '15 minutes', '15 minutes', 'active');

